# Generates src/build_hash.g.odin: a content hash of every non-generated .odin source file.
# Run from build.bat before 'odin build' so each build embeds the hash of what it compiled.
# The hash is SHA-256 over the sorted source files' bytes, truncated to 12 hex chars.
param([string]$OutFile = "src/build_hash.g.odin")

$ErrorActionPreference = "Stop"

# Resolve paths relative to the repo root (tool/..) so this works regardless of caller CWD.
$toolDir = Split-Path -Parent $MyInvocation.MyCommand.Path
$repo    = Split-Path -Parent $toolDir
$srcDir  = Join-Path $repo "src"

$files = Get-ChildItem -Path $srcDir -Recurse -Filter *.odin |
    Where-Object { $_.Name -notlike "*.g.odin" } |
    Sort-Object FullName

$ms = New-Object System.IO.MemoryStream
foreach ($f in $files) {
    $bytes = [System.IO.File]::ReadAllBytes($f.FullName)
    $ms.Write($bytes, 0, $bytes.Length)
}
$ms.Position = 0

$sha    = [System.Security.Cryptography.SHA256]::Create()
$digest = $sha.ComputeHash($ms)
$hex    = ($digest | ForEach-Object { $_.ToString("x2") }) -join ""
$short  = $hex.Substring(0, 12)

$content = @"
// THIS FILE IS GENERATED BY tool/gen_build_hash.ps1 (invoked from build.bat). DO NOT EDIT.
package main

BUILD_HASH :: "$short"
"@

# Write UTF-8 without a BOM - Odin's tokenizer chokes on a leading BOM.
$outPath = Join-Path $repo $OutFile
$enc = New-Object System.Text.UTF8Encoding($false)
[System.IO.File]::WriteAllText($outPath, $content, $enc)

Write-Host "build hash: $short ($($files.Count) source files)"
